ignore:
  - "*_gen.go"
  - "tools"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

  range: 50..75
  round: down
  precision: 1
