// Generated by genstorage. DO NOT EDIT.

package main

import "github.com/ErikKalkoken/go-set"


func (st *Storage) ListEveAlliance() ([]EveAlliance, error) {
    return listEveObjects[EveAlliance](st, bucketEveAlliance)
}

func (st *Storage) ListFreshEveAllianceByID(ids set.Set[int64]) ([]EveAlliance, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveAlliance](st, bucketEveAlliance, ids)
}

func (st *Storage) UpdateOrCreateEveAlliance(objs []EveAlliance) error {
    return updateOrCreateEveObjects(st, bucketEveAlliance, objs)
}


func (st *Storage) ListEveCategory() ([]EveCategory, error) {
    return listEveObjects[EveCategory](st, bucketEveCategory)
}

func (st *Storage) ListFreshEveCategoryByID(ids set.Set[int64]) ([]EveCategory, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveCategory](st, bucketEveCategory, ids)
}

func (st *Storage) UpdateOrCreateEveCategory(objs []EveCategory) error {
    return updateOrCreateEveObjects(st, bucketEveCategory, objs)
}


func (st *Storage) ListEveCharacter() ([]EveCharacter, error) {
    return listEveObjects[EveCharacter](st, bucketEveCharacter)
}

func (st *Storage) ListFreshEveCharacterByID(ids set.Set[int64]) ([]EveCharacter, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveCharacter](st, bucketEveCharacter, ids)
}

func (st *Storage) UpdateOrCreateEveCharacter(objs []EveCharacter) error {
    return updateOrCreateEveObjects(st, bucketEveCharacter, objs)
}


func (st *Storage) ListEveConstellation() ([]EveConstellation, error) {
    return listEveObjects[EveConstellation](st, bucketEveConstellation)
}

func (st *Storage) ListFreshEveConstellationByID(ids set.Set[int64]) ([]EveConstellation, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveConstellation](st, bucketEveConstellation, ids)
}

func (st *Storage) UpdateOrCreateEveConstellation(objs []EveConstellation) error {
    return updateOrCreateEveObjects(st, bucketEveConstellation, objs)
}


func (st *Storage) ListEveCorporation() ([]EveCorporation, error) {
    return listEveObjects[EveCorporation](st, bucketEveCorporation)
}

func (st *Storage) ListFreshEveCorporationByID(ids set.Set[int64]) ([]EveCorporation, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveCorporation](st, bucketEveCorporation, ids)
}

func (st *Storage) UpdateOrCreateEveCorporation(objs []EveCorporation) error {
    return updateOrCreateEveObjects(st, bucketEveCorporation, objs)
}


func (st *Storage) ListEveEntity() ([]EveEntity, error) {
    return listEveObjects[EveEntity](st, bucketEveEntity)
}

func (st *Storage) ListFreshEveEntityByID(ids set.Set[int64]) ([]EveEntity, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveEntity](st, bucketEveEntity, ids)
}

func (st *Storage) UpdateOrCreateEveEntity(objs []EveEntity) error {
    return updateOrCreateEveObjects(st, bucketEveEntity, objs)
}


func (st *Storage) ListEveFaction() ([]EveFaction, error) {
    return listEveObjects[EveFaction](st, bucketEveFaction)
}

func (st *Storage) ListFreshEveFactionByID(ids set.Set[int64]) ([]EveFaction, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveFaction](st, bucketEveFaction, ids)
}

func (st *Storage) UpdateOrCreateEveFaction(objs []EveFaction) error {
    return updateOrCreateEveObjects(st, bucketEveFaction, objs)
}


func (st *Storage) ListEveGroup() ([]EveGroup, error) {
    return listEveObjects[EveGroup](st, bucketEveGroup)
}

func (st *Storage) ListFreshEveGroupByID(ids set.Set[int64]) ([]EveGroup, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveGroup](st, bucketEveGroup, ids)
}

func (st *Storage) UpdateOrCreateEveGroup(objs []EveGroup) error {
    return updateOrCreateEveObjects(st, bucketEveGroup, objs)
}


func (st *Storage) ListEveRegion() ([]EveRegion, error) {
    return listEveObjects[EveRegion](st, bucketEveRegion)
}

func (st *Storage) ListFreshEveRegionByID(ids set.Set[int64]) ([]EveRegion, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveRegion](st, bucketEveRegion, ids)
}

func (st *Storage) UpdateOrCreateEveRegion(objs []EveRegion) error {
    return updateOrCreateEveObjects(st, bucketEveRegion, objs)
}


func (st *Storage) ListEveSolarSystem() ([]EveSolarSystem, error) {
    return listEveObjects[EveSolarSystem](st, bucketEveSolarSystem)
}

func (st *Storage) ListFreshEveSolarSystemByID(ids set.Set[int64]) ([]EveSolarSystem, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveSolarSystem](st, bucketEveSolarSystem, ids)
}

func (st *Storage) UpdateOrCreateEveSolarSystem(objs []EveSolarSystem) error {
    return updateOrCreateEveObjects(st, bucketEveSolarSystem, objs)
}


func (st *Storage) ListEveStation() ([]EveStation, error) {
    return listEveObjects[EveStation](st, bucketEveStation)
}

func (st *Storage) ListFreshEveStationByID(ids set.Set[int64]) ([]EveStation, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveStation](st, bucketEveStation, ids)
}

func (st *Storage) UpdateOrCreateEveStation(objs []EveStation) error {
    return updateOrCreateEveObjects(st, bucketEveStation, objs)
}


func (st *Storage) ListEveType() ([]EveType, error) {
    return listEveObjects[EveType](st, bucketEveType)
}

func (st *Storage) ListFreshEveTypeByID(ids set.Set[int64]) ([]EveType, set.Set[int64], error) {
    return listFreshEveObjectsByID[EveType](st, bucketEveType, ids)
}

func (st *Storage) UpdateOrCreateEveType(objs []EveType) error {
    return updateOrCreateEveObjects(st, bucketEveType, objs)
}

