# Workflow for testing and releasing

name: CI/CD

env:
  GOVERSION: "1.24.3"
  NAME: "elt"
  VERSION: "0.0.0"

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -coverprofile=coverage.txt ./...

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install zip gzip tar

    - name: Set version
      run: |
        VERSION=${{ github.ref_name }}
        echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

    - name: Build linux
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.VERSION }}" -o ./build/linux/ .

    - name: Package linux
      run: tar --directory=build/linux -czvf ${{ env.NAME }}-${{ env.VERSION }}-linux-amd64.tar.gz ${{ env.NAME }}

    - name: Build windows
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.VERSION }}" -o ./build/windows/ .

    - name: Package windows
      run: zip -j ${{ env.NAME }}-${{ env.VERSION }}-windows-amd64.zip ./build/windows/${{ env.NAME }}.exe

    - name: Build darwin
      run: GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.VERSION }}" -o ./build/darwin/ .

    - name: Package darwin
      run: zip -j ${{ env.NAME }}-${{ env.VERSION }}-darwin-amd64.zip ./build/darwin/${{ env.NAME }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        files: |
          ${{ env.NAME }}-${{ env.VERSION }}-darwin-amd64.zip
          ${{ env.NAME }}-${{ env.VERSION }}-linux-amd64.tar.gz
          ${{ env.NAME }}-${{ env.VERSION }}-windows-amd64.zip